import { Container } from "@mui/material";
import TopBar from "../components/TopBar";
import Footer from "../components/Footer";
import { HEADERHEIGHT } from "@/theme";

export const metadata = {
  title: "Beglarian Fabrics",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      <TopBar headerHeight={HEADERHEIGHT} />
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          pb: "32px",
          pt: `${HEADERHEIGHT + 32}px`,
          minHeight: `100vh`,
        }}
      >
        {children}
      </Container>
      <Footer />
    </>
  );
}
