const MEDIA_IMAGE_BASE_URL = `${process.env.NEXT_PUBLIC_MEDIA_URL}/image`;
const MEDIA_VIDEO_BASE_URL = `${process.env.NEXT_PUBLIC_MEDIA_URL}/video`;

export { MEDIA_IMAGE_BASE_URL, MEDIA_VIDEO_BASE_URL };
