// "use client"

import { Container } from "@mui/material";
import TopBar from "./components/TopBar";
import { Providers } from "./provider";
import Footer from "./components/Footer";

// export const metadata = {
//   title: "24.03",
//   description: "Generated by create next app",
// };

export const headerHeight = 64;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#F7F8FC" }}>
        <Providers>
          <TopBar headerHeight={headerHeight} />
          <Container
            sx={{
              display: "flex",
              flexDirection: "column",
              pb: "32px",
              pt: `${headerHeight + 32}px`,
              minHeight: `100vh`,
            }}
          >
            {children}
          </Container>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
